import type { Land } from "@/lib/types";

// ============================================================
// Date demo pentru listări (vor fi înlocuite cu date din Supabase)
// Folosite atât pe homepage cât și pe pagina de detalii
// ============================================================
export const DEMO_LANDS: Land[] = [
  {
    id: "1",
    created_at: "2026-04-08T10:00:00Z",
    updated_at: "2026-04-08T10:00:00Z",
    titlu: "Hectar intravilan lângă pădure — ideal pentru casă",
    descriere:
      "Hectar plat cu acces la utilități, vecini liniștiți, la 5 minute de centrul localității Florești. Situat într-o zonă rezidențială în plină dezvoltare, cu acces facil la toate facilitățile urbane.\n\nHectarul beneficiază de:\n• Acces la rețeaua de apă și canalizare\n• Gaz la limita proprietății\n• Electricitate la poartă\n• Drum asfaltat\n• Vecinătăți liniștite, ideale pentru familie\n\nPerfect pentru construcția unei case unifamiliale sau duplex. Documentație completă și la zi, fără sarcini sau litigii.",
    pret: 45000,
    suprafata_mp: 800,
    localitate: "Florești",
    judet: "Cluj",
    tip_hectar: "intravilan",
    latitudine: 46.743,
    longitudine: 23.496,
    imagini: ["/land-1.png", "/land-2.png", "/land-3.png", "/land-4.png"],
    status: "disponibil",
    has_curent: true,
    has_apa: true,
    has_gaz: true,
    has_canalizare: true,
  },
  {
    id: "2",
    created_at: "2026-04-07T14:30:00Z",
    updated_at: "2026-04-07T14:30:00Z",
    titlu: "Hectar extravilan agricol — zonă fertilă",
    descriere:
      "Hectar agricol de clasă premium, acces la drum asfaltat. Sol fertil, ideal pentru cultură de cereale sau livadă. Zonă cu potențial mare de investiție, în apropierea autostrăzii.\n\nCaracteristici:\n• Sol de categoria I de fertilitate\n• Acces la drum comunal asfaltat\n• Parcelă regulată, ușor de exploatat\n• Vecini cu exploatări agricole active\n• Posibilitate de dezvoltare agricolă",
    pret: 28000,
    suprafata_mp: 5000,
    localitate: "Moșnița Nouă",
    judet: "Timiș",
    tip_hectar: "extravilan",
    latitudine: 45.693,
    longitudine: 21.178,
    imagini: ["/land-2.png", "/land-4.png", "/land-1.png"],
    status: "disponibil",
    has_curent: false,
    has_apa: false,
    has_gaz: false,
    has_canalizare: false,
  },
  {
    id: "3",
    created_at: "2026-04-06T09:15:00Z",
    updated_at: "2026-04-06T09:15:00Z",
    titlu: "Hectar cu vedere panoramică la munte",
    descriere:
      "Locație spectaculoasă pe deal, perfect pentru pensiune turistică. Vedere la 180° spre Munții Cindrel, aer curat, liniște totală.\n\nBeneficii:\n• Panoramă spectaculoasă spre munți\n• Zonă turistică cu potențial ridicat\n• Acces la utilități (curent electric, apă)\n• Drum de acces pietruit, întreținut\n• PUZ aprobat pentru construcție P+1+M",
    pret: 75000,
    suprafata_mp: 1200,
    localitate: "Rășinari",
    judet: "Sibiu",
    tip_hectar: "intravilan",
    latitudine: 45.678,
    longitudine: 24.289,
    imagini: ["/land-3.png", "/land-6.png", "/land-5.png"],
    status: "disponibil",
    has_curent: true,
    has_apa: true,
    has_gaz: false,
    has_canalizare: false,
  },
  {
    id: "4",
    created_at: "2026-04-05T16:00:00Z",
    updated_at: "2026-04-05T16:00:00Z",
    titlu: "Hectar agricol la marginea pădurii",
    descriere:
      "Suprafață mare la marginea pădurii, ideal pentru investiție pe termen lung sau fermă ecologică.\n\nDetalii:\n• 10.000 mp la limita pădurii de foioase\n• Sol fertil, utilizat anterior pentru pășunat\n• Acces la drum forestier\n• Posibilitate de dezvoltare eco-turism\n• Zonă liniștită, fauna sălbatică prezentă",
    pret: 35000,
    suprafata_mp: 10000,
    localitate: "Săcele",
    judet: "Brașov",
    tip_hectar: "extravilan",
    latitudine: 45.618,
    longitudine: 25.697,
    imagini: ["/land-4.png", "/land-1.png", "/land-2.png"],
    status: "rezervat",
    has_curent: false,
    has_apa: false,
    has_gaz: false,
    has_canalizare: false,
  },
  {
    id: "5",
    created_at: "2026-04-04T11:45:00Z",
    updated_at: "2026-04-04T11:45:00Z",
    titlu: "Hectar pentru construcție în cartier rezidențial",
    descriere:
      "Hectar intravilan, toate utilitățile la poartă, stradă asfaltată. Cartier nou, cu vile recent construite.\n\nAvantaje:\n• Toate utilitățile la poartă (apă, gaz, curent, canalizare)\n• Stradă asfaltată cu iluminat public\n• Vecinătăți cu case noi\n• La 15 minute de București\n• Transport public la 200m",
    pret: 62000,
    suprafata_mp: 500,
    localitate: "Voluntari",
    judet: "Ilfov",
    tip_hectar: "intravilan",
    latitudine: 44.493,
    longitudine: 26.159,
    imagini: ["/land-5.png", "/land-2.png", "/land-3.png"],
    status: "disponibil",
    has_curent: true,
    has_apa: true,
    has_gaz: true,
    has_canalizare: true,
  },
  {
    id: "6",
    created_at: "2026-04-03T08:20:00Z",
    updated_at: "2026-04-03T08:20:00Z",
    titlu: "Hectar cu lac — oportunitate unică",
    descriere:
      "Hectar pe malul lacului Snagov, ideal pentru cabana de weekend sau investiție turistică. Acces direct la lac.\n\nCaracteristici unice:\n• Deschidere la lac de 30 metri liniari\n• Ponton privat posibil\n• Zonă de agrement și pescuit\n• Pădure de stejar în vecinătate\n• Acces rutier excelent",
    pret: 120000,
    suprafata_mp: 2500,
    localitate: "Snagov",
    judet: "Ilfov",
    tip_hectar: "intravilan",
    latitudine: 44.697,
    longitudine: 26.153,
    imagini: ["/land-6.png", "/land-3.png", "/land-5.png", "/land-1.png"],
    status: "disponibil",
    has_curent: false,
    has_apa: false,
    has_gaz: false,
    has_canalizare: false,
  },
  {
    id: "7",
    created_at: "2026-04-02T13:00:00Z",
    updated_at: "2026-04-02T13:00:00Z",
    titlu: "Hectar extravilan — afacere viticolă",
    descriere:
      "Hectar pe deal sudic, sol ideal pentru viță de vie sau livadă. Expoziție excelentă.\n\nDetalii:\n• Expoziție sud-est, ideală pentru viticultură\n• Sol argilos-calcaros\n• Zonă DOC Recaș\n• Acces la drum comunal\n• Infrastructură de irigații în apropiere",
    pret: 18000,
    suprafata_mp: 8000,
    localitate: "Recaș",
    judet: "Timiș",
    tip_hectar: "extravilan",
    latitudine: 45.796,
    longitudine: 21.544,
    imagini: ["/land-1.png", "/land-4.png"],
    status: "disponibil",
    has_curent: false,
    has_apa: false,
    has_gaz: false,
    has_canalizare: false,
  },
  {
    id: "8",
    created_at: "2026-04-01T15:30:00Z",
    updated_at: "2026-04-01T15:30:00Z",
    titlu: "Hectar construcție în zona metropolitană",
    descriere:
      "Hectar perfect pentru un bloc mic sau complex rezidențial, în zona metropolitană a Bucureștiului.\n\nSpecificații:\n• PUZ aprobat pentru P+4\n• CUT 2.5, POT 40%\n• Toate utilitățile la limita proprietății\n• Stație de metrou la 1 km\n• Acces facil la centură și autostradă",
    pret: 195000,
    suprafata_mp: 3000,
    localitate: "Popești-Leordeni",
    judet: "Ilfov",
    tip_hectar: "intravilan",
    latitudine: 44.372,
    longitudine: 26.163,
    imagini: ["/land-2.png", "/land-5.png", "/land-6.png"],
    status: "disponibil",
    has_curent: true,
    has_apa: true,
    has_gaz: true,
    has_canalizare: true,
  },
  {
    id: "9",
    created_at: "2026-03-30T10:00:00Z",
    updated_at: "2026-03-30T10:00:00Z",
    titlu: "Hectar în sat turistic — zonă montană",
    descriere:
      "Locație perfectă pentru pensiune turistică, aproape de Castelul Bran și pârtiile de ski.\n\nAvantaje:\n• La 2 km de Castelul Bran\n• Zonă turistică de top\n• Vedere la masivul Bucegi\n• Acces la utilități complete\n• Autorizație de construcție obținută",
    pret: 89000,
    suprafata_mp: 1500,
    localitate: "Bran",
    judet: "Brașov",
    tip_hectar: "intravilan",
    latitudine: 45.513,
    longitudine: 25.357,
    imagini: ["/land-3.png", "/land-6.png", "/land-4.png"],
    status: "vandut",
    has_curent: true,
    has_apa: true,
    has_gaz: true,
    has_canalizare: true,
  },
];
